# Generated by Django 2.2.7 on 2019-11-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(verbose_name='Key')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(verbose_name='Key')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('enable', models.BooleanField(verbose_name='Enable')),
                ('unit', models.CharField(choices=[(1, 'ºC'), (2, 'mg/m³'), (3, 'hPA'), (4, 'lux'), (5, '%')], max_length=3)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='TimeStamp')),
                ('value', models.FloatField(verbose_name='Value')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stream')),
            ],
        ),
    ]
