# Generated by Django 2.2.7 on 2019-11-06 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191106_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
